export const nameBand = 'HOW TO TRAIN YOUR DRAGON';
export let nameSongs = [
	"TEST DRIVE", /*1*/
	"DRAGON TRAINING", /*2*/
	"THIS IS BERK", /*3*/
	"DRAGON RACING ", /*4*/
	"SEE YOU TOMORROW", /*5*/
	"BATTLE OF THE GREEN DEATH", /*6*/
	"THE DOWNED DRAGON", /*7*/
	"ROMANTIC FLIGHT", /*8*/
	"COMING BACK AROUND", /*9*/
	"NEW TAIL", /*10*/
	"READY THE SHIPS", /*11*/
	"THE KILL RING", /*12*/
	"COUNTER ATTACK", /*13*/
	"WHERE'S HICCUP?", /*14*/
	"DRAGON'S DEN", /*15*/
	"TOOTHLESS FOUND", /*16*/
	"TWO NEW ALPHAS", /*17*/
	"FORBIDDEN FRIENDSHIP", /*18*/
	"BATTLE OF THE BEWILDERBEAST", /*19*/
	"HICCUP CONFRONTS DRAGO", /*20*/
]